Traceback (most recent call last):
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\gabri\anaconda3\envs\book\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\gabri\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
c1 = Complexe(2,3)
c2 = Complexe(3,4)

c1.real = "matematics" # canviam el tipus d'una variable de enter a string

c3 = c1.suma(c2) # aixo dona error ja que no pot sumar un string amb un enter
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-9-80d2d4c383d2>[0m in [0;36m<module>[1;34m[0m
[0;32m      4[0m [0mc1[0m[1;33m.[0m[0mreal[0m [1;33m=[0m [1;34m"matematics"[0m [1;31m# canviam el tipus d'una variable de enter a string[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m
[1;32m----> 6[1;33m [0mc3[0m [1;33m=[0m [0mc1[0m[1;33m.[0m[0msuma[0m[1;33m([0m[0mc2[0m[1;33m)[0m [1;31m# aixo dona error ja que no pot sumar un string amb un enter[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m<ipython-input-8-67fa5146f25b>[0m in [0;36msuma[1;34m(self, o)[0m
[0;32m      8[0m         [1;31m# Metode[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m     [1;32mdef[0m [0msuma[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mo[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 10[1;33m         [0mr[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mreal[0m [1;33m+[0m [0mo[0m[1;33m.[0m[0mreal[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m         [0mi[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mimaginaria[0m [1;33m+[0m [0mo[0m[1;33m.[0m[0mimaginaria[0m[1;33m[0m[1;33m[0m[0m
[0;32m     12[0m         [1;32mreturn[0m [0mComplexe[0m[1;33m([0m[0mr[0m[1;33m,[0m [0mi[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: can only concatenate str (not "int") to str
TypeError: can only concatenate str (not "int") to str

